name: Build and deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - run: dotnet build --configuration Release
        working-directory: ./PersonalNotesAPI
      - run: dotnet publish -c Release -o ./publish
        working-directory: ./PersonalNotesAPI
      - uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./PersonalNotesAPI/publish

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./myapp
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_... }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_... }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_... }}
      - uses: azure/webapps-deploy@v3
        with:
          app-name: 'personal-notes-api'
          package: ./myapp